# Generated by Django 3.1.1 on 2021-02-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, help_text='Дата рождения пользователя', null=True, verbose_name='Дата рождения'),
        ),
    ]
