# Generated by Django 3.1.1 on 2021-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210225_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.TimeField(),
        ),
    ]
