# Generated by Django 3.1.1 on 2021-02-25 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='likes',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='image_likes',
            field=models.ManyToManyField(blank=True, related_name='image_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
