# Generated by Django 3.1.1 on 2021-02-26 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
