# Generated by Django 3.1.1 on 2021-03-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210308_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
