# Generated by Django 3.1.1 on 2021-03-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210308_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encoded_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
